/**
 * Règles intégrées : CMP (sélecteurs), textes cookies, textes modales.
 * Les listes sont composées côté content.js selon le mode (all / cookies / modals).
 */
var QUIET_RULES = {
  hideSelectors: [
    "#onetrust-banner-sdk",
    "#onetrust-consent-sdk",
    ".onetrust-pc-dark-filter",
    "#CybotCookiebotDialog",
    "#CybotCookiebotDialogBodyUnderlay",
    "#cookiescript_injected",
    "#cookiescript_injected_wrapper",
    "#qc-cmp2-ui",
    "#sp-cc-wrapper",
    "#sp_message_container",
    "#ncmp__tool",
    "#ncmp__banner",
    "#ncmp__modal",
    "#tcf-footer",
    "#tarteaucitronRoot",
    "#tarteaucitronAlertBig",
    ".tarteaucitronBeforeVisible",
    "#cookie-law-info-bar",
    "#cookie-law-info-again",
    "#cliSettingsPopup",
    "#cmplz-cookiebanner-container",
    "#cmplz-manage-consent",
    ".cc-window",
    ".cc-banner",
    "#cookieConsent",
    "#cookie-consent",
    "#cookieconsent",
    "#cookieConsentBanner",
    "#cookie-banner",
    "#cookieBanner",
    ".cookie-banner",
    ".cookie-notice",
    ".cookie-notice-container",
    "#eu-cookie-law",
    "#privacy-overlay",
    "#usercentrics-root",
    "#uc-banner",
    "#uc-corner-modal",
    "#didomi-host",
    ".didomi-popup-container",
    "#trustarc-banner",
    "#notice",
    ".truste_box_overlay",
    "#cconsent-bar",
    "#cookiefirst-root",
    "#CookiebotDialog",
    "#axeptio_overlay",
    "#axeptio_widget",
    "#klaro",
    ".klaro",
    "#orejime",
    ".orejime-Root",
    "#cookies-policy-popup",
    "#pnl-cookie",
    "#js-cookie-consent",
    ".js-cookie-consent",
    "#gdpr-consent",
    ".gdpr-banner",
    "#termly-code-snippet-support",
    ".termly-styles",
    "#osano-cm-dom-info",
    ".osano-cm-window",
    "#adopt-controller-button",
    "#adopt-modal",
    "#funding-choices",
    ".fc-dialog",
    ".fc-consent-root",
    "#ez-cookie-dialog-wrapper",
    "#ezmobfooter",
    "#ezmob-consent",
    "#__cmp__",
    "#civic-cookie-control",
    ".ccc-widget",
    "#moove_gdpr_cookie_modal",
    "#moove_gdpr_cookie_info_bar",
    "#borlabs-cookie",
    ".borlabs-modal",
    "#rl-privacy-consent",
    "#privacy-consent",
    "#privacy-banner",
    "#privacy-popup",
    "#wp-gdpr-cookie-notice-wrap",
    "#cookiehint",
    "#cookienotice",
    "#cookieNotice",
    "#cookie-notice-bar",
    "#shopify-pc__banner",
    "#shopify-pc__prefs__dialog",
    "#shopify-pc__banner__dialog",
    "#shopify-pc__banner__backdrop",
    "#shopify-pc__prefs__backdrop",
    "#pandectes-banner",
    "#pandectes-root",
    "#transcend-consent-manager",
    "#transcend-consent",
    "#ensModalWrapper",
    "#ensNotifyBanner",
    "#ensModal",
    "#ensPrivacyBanner",
    "#ensPrivacyModal",
    "#ensModalBackdrop",
    "#ensPrivacyBackdrop"
  ],

  cookieTextNeedles: [
    "we use cookies",
    "nous utilisons des cookies",
    "this site uses cookies",
    "cookie preferences",
    "paramètres des cookies",
    "consentement",
    "accept all cookies",
    "tout accepter",
    "reject all",
    "tout refuser",
    "manage preferences",
    "gérer les préférences",
    "privacy policy",
    "politique de confidentialité",
    "gdpr",
    "rgpd"
  ],

  modalTextNeedles: [
    "adblock",
    "ad blocker",
    "ad-blocker",
    "bloqueur de pub",
    "bloqueur de publicité",
    "désactivez votre bloqueur",
    "desactivez votre bloqueur",
    "disable your ad blocker",
    "please disable",
    "whitelist",
    "liste blanche",
    "turn off your ad",
    "support us by disabling",
    "newsletter",
    "inscrivez-vous",
    "subscribe now",
    "sign up for",
    "créez un compte",
    "create an account",
    "register for free",
    "join our mailing",
    "get our newsletter",
    "promo code",
    "limited time offer",
    "paywall",
    "abonnez-vous",
    "subscription required"
  ],

  strongModalNeedles: [
    "adblock",
    "ad blocker",
    "bloqueur de pub",
    "disable your ad",
    "désactivez votre bloqueur",
    "whitelist",
    "liste blanche"
  ]
};
